# Generated by Django 4.0.1 on 2022-06-29 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newsstory_story_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='newsstory',
            name='story_img',
        ),
    ]
