# Generated by Django 4.0.1 on 2022-07-01 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_newsstory_category_remove_newsstory_story_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='newsstory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newsstory'),
        ),
    ]
